package com.kaneki.done.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kaneki.done.model.entity.DayEntity;
import com.kaneki.done.model.entity.DoneEntity;

import com.kaneki.done.db.DayEntityDao;
import com.kaneki.done.db.DoneEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayEntityDaoConfig;
    private final DaoConfig doneEntityDaoConfig;

    private final DayEntityDao dayEntityDao;
    private final DoneEntityDao doneEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayEntityDaoConfig = daoConfigMap.get(DayEntityDao.class).clone();
        dayEntityDaoConfig.initIdentityScope(type);

        doneEntityDaoConfig = daoConfigMap.get(DoneEntityDao.class).clone();
        doneEntityDaoConfig.initIdentityScope(type);

        dayEntityDao = new DayEntityDao(dayEntityDaoConfig, this);
        doneEntityDao = new DoneEntityDao(doneEntityDaoConfig, this);

        registerDao(DayEntity.class, dayEntityDao);
        registerDao(DoneEntity.class, doneEntityDao);
    }
    
    public void clear() {
        dayEntityDaoConfig.clearIdentityScope();
        doneEntityDaoConfig.clearIdentityScope();
    }

    public DayEntityDao getDayEntityDao() {
        return dayEntityDao;
    }

    public DoneEntityDao getDoneEntityDao() {
        return doneEntityDao;
    }

}
